### ISSUE TITLE
Does not run on Windows

### ISSUE THREAD

**Issue by Granjow** [substack/adventure#10]
I tried Git Bash, cmd, cygwin, and either the arrow keys do not work in the menu or (Cygwin) it does not start at all.

Is there a way to at least get the menu running on Windows?

**Comment by yoshuawuyts** [comment]
Good question. I don't have access to a window machine and don't know anyone who does, so if you're comfortable enough doing it you might want to dig in yourself. Sorry I can't be of more help right now, perhaps someone else can be (':

**Comment by Granjow** [comment]
Appears to be a node.js 4.x problem.
https://github.com/nodeschool/discussions/issues/1448

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0

**Comment by Granjow** [comment]
Indeed! Very cool. Thanks for the update.
